export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_VACATIONS_STARTS = 'FETCH_VACATIONS_STARTS';
export const FETCH_VACATIONS_SUCCESS = 'FETCH_VACATIONS_SUCCESS';
export const FETCH_VACATIONS_FAIL = 'FETCH_VACATIONS_FAIL';

export const SET_VACATIONS = 'SET_VACATIONS';

export const ADD_VACATION_TO_FAVORITES_SUCCESS = 'ADD_VACATION_TO_FAVORITES_SUCCESS';
export const ADD_VACATION_TO_FAVORITES_FAIL = 'ADD_VACATION_TO_FAVORITES_FAIL';
export const REMOVE_VACATION_FROM_VAFORITES_SUCCESS = 'REMOVE_VACATION_FROM_VAFORITES_SUCCESS';
export const REMOVE_VACATION_FROM_VAFORITES_FAIL = 'REMOVE_VACATION_FROM_VAFORITES_FAIL';
export const GET_USER_FAVORITES_VACATIONS_SUCCESS = 'GET_USER_FAVORITES_VACATIONS_SUCCESS';
export const GET_USER_FAVORITES_VACATIONS_FAIL = 'GET_USER_FAVORITES_VACATIONS_FAIL';

export const ADD_VACATION_SUCCESS = 'ADD_VACATION_SUCCESS';
export const ADD_VACATION_FAIL = 'ADD_VACATION_FAIL';
export const REMOVE_VACATION_SUCCESS = 'REMOVE_VACATION_SUCCESS';
export const REMOVE_VACATION_FAIL = 'REMOVE_VACATION_FAIL';
export const SET_ADD_VACATION_REDIRECT_PATH = 'SET_ADD_VACATION_REDIRECT_PATH';
export const UPDATE_VACATION_SUCCESS = 'UPDATE_VACATION_SUCCESS';
export const UPDATE_VACATION_FAIL = 'UPDATE_VACATION_FAIL';